import type { Service, Testimonial, CaseStudy, BlogPost, CatalogItem, TeamMember, FAQItem } from "@/types/content";

export const mockServices: Service[] = [
  {
    slug: "residential-wiring",
    title: "Residential Wiring",
    category: "Residential",
    shortDescription: "Complete home wiring, rewiring and circuit upgrades for safe, modern power distribution.",
    pricingRange: "$150–$2,500",
    responseWindow: "Same day",
    trustBadge: "Licensed & Insured",
    icon: "home",
    featured: true,
  },
  {
    slug: "panel-upgrades",
    title: "Panel Upgrades",
    category: "Residential",
    shortDescription: "Upgrade your electrical panel to handle today's power demands safely and efficiently.",
    pricingRange: "$800–$3,500",
    responseWindow: "Next day",
    trustBadge: "Code Compliant",
    icon: "zap",
    featured: true,
  },
  {
    slug: "emergency-repair",
    title: "Emergency Repair",
    category: "Emergency",
    shortDescription: "24/7 emergency electrical repairs. Fast response to power outages, sparks and tripped breakers.",
    pricingRange: "$200–$1,200",
    responseWindow: "< 1 hour",
    trustBadge: "24/7 Available",
    icon: "alert-triangle",
    featured: true,
  },
  {
    slug: "generator-installation",
    title: "Generator Installation",
    category: "Specialty",
    shortDescription: "Whole-home and commercial generator installation with automatic transfer switches.",
    pricingRange: "$3,000–$15,000",
    responseWindow: "Scheduled",
    trustBadge: "Factory Certified",
    icon: "cpu",
    featured: true,
  },
  {
    slug: "ev-charger-installation",
    title: "EV Charger Installation",
    category: "Specialty",
    shortDescription: "Level 2 and DC fast charger installation for residential garages and commercial lots.",
    pricingRange: "$500–$2,000",
    responseWindow: "Next day",
    trustBadge: "EV Certified",
    icon: "battery-charging",
  },
  {
    slug: "commercial-electrical",
    title: "Commercial Electrical",
    category: "Commercial",
    shortDescription: "Full commercial electrical services — tenant fit-outs, lighting design, power distribution.",
    pricingRange: "Custom quote",
    responseWindow: "Scheduled",
    trustBadge: "Commercial Licensed",
    icon: "building",
  },
  {
    slug: "lighting-installation",
    title: "Lighting Installation",
    category: "Residential",
    shortDescription: "Interior and exterior lighting, smart lighting control systems and LED retrofits.",
    pricingRange: "$100–$1,500",
    responseWindow: "Same day",
    trustBadge: "5-Star Rated",
    icon: "lightbulb",
  },
  {
    slug: "electrical-inspection",
    title: "Electrical Inspection",
    category: "Maintenance",
    shortDescription: "Comprehensive electrical safety inspections for pre-purchase, insurance and peace of mind.",
    pricingRange: "$150–$400",
    responseWindow: "Next day",
    trustBadge: "Certified Inspector",
    icon: "shield-check",
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: "1",
    customerName: "Sarah M.",
    location: "Springfield",
    serviceUsed: "Panel Upgrades",
    rating: 5,
    quote: "Absolutely fantastic service. The team upgraded our 100A panel to 200A in one day. Clean work, fully permitted. Our house feels safe for the first time in years.",
    date: "2025-04-12",
    category: "Residential",
  },
  {
    id: "2",
    customerName: "James R.",
    location: "Shelbyville",
    serviceUsed: "Emergency Repair",
    rating: 5,
    quote: "Called at 2am after a power surge. Technician was at our door within 45 minutes. Diagnosed and fixed the issue in under 2 hours. Outstanding response time.",
    date: "2025-03-28",
    category: "Emergency",
  },
  {
    id: "3",
    customerName: "Linda K.",
    location: "Capital City",
    serviceUsed: "EV Charger Installation",
    rating: 5,
    quote: "Fast installation, competitive pricing, and they handled the utility rebate paperwork. Would absolutely recommend to any EV owner.",
    date: "2025-05-01",
    category: "Specialty",
  },
  {
    id: "4",
    customerName: "Tom B.",
    location: "Springfield",
    serviceUsed: "Commercial Electrical",
    rating: 5,
    quote: "PowerPro handled our entire office renovation — 4,000 sq ft, 80 circuits. Finished ahead of schedule and under budget. Professional team throughout.",
    date: "2025-02-15",
    category: "Commercial",
  },
  {
    id: "5",
    customerName: "Maria S.",
    location: "Ogdenville",
    serviceUsed: "Residential Wiring",
    rating: 5,
    quote: "Complete rewire of our 1960s home. The crew was respectful, clean and explained everything. The permit passed first inspection. Highly recommend.",
    date: "2025-01-20",
    category: "Residential",
  },
  {
    id: "6",
    customerName: "David P.",
    location: "North Haverbrook",
    serviceUsed: "Generator Installation",
    rating: 5,
    quote: "Our generator has saved us three times this winter. Installation was smooth and the automatic transfer switch works perfectly. Best investment we made.",
    date: "2024-12-10",
    category: "Specialty",
  },
];

export const mockCaseStudies: CaseStudy[] = [
  {
    slug: "historic-home-rewire-springfield",
    title: "Full Rewire of 1920s Historic Home in Springfield",
    location: "Springfield",
    category: "Residential Wiring",
    propertyType: "Residential",
    challenge: "A 1,800 sq ft historic home with original knob-and-tube wiring was a fire hazard and failed to meet insurance requirements.",
    solution: "Full rewire with modern copper wiring, 200A panel upgrade, AFCI breakers throughout, and preservation-compliant installation methods.",
    outcome: "100% code compliance, insurance approval, and a 40% reduction in electrical incidents.",
    duration: "8 days",
    featured: true,
  },
  {
    slug: "commercial-office-fit-out-capital-city",
    title: "4,000 sq ft Office Electrical Fit-Out",
    location: "Capital City",
    category: "Commercial Electrical",
    propertyType: "Commercial",
    challenge: "A fast-growing tech firm needed a full electrical fit-out for a leased office, including server room, 40 workstations and conference AV.",
    solution: "Dedicated server room circuit with redundant UPS paths, structured wiring, LED lighting controls, and 80 individual circuits.",
    outcome: "Delivered 3 days ahead of schedule. Zero punch list items after final inspection.",
    duration: "12 days",
    featured: true,
  },
  {
    slug: "ev-charging-station-shelbyville",
    title: "Multi-Bay EV Charging Station for Auto Dealership",
    location: "Shelbyville",
    category: "EV Charger Installation",
    propertyType: "Commercial",
    challenge: "An auto dealership needed 12 Level 2 EV chargers across their lot within a tight 5-day window before a manufacturer audit.",
    solution: "Panel upgrade to 400A service, trenching, conduit installation, and 12 smart charger deployments with fleet management software integration.",
    outcome: "Passed manufacturer audit. Dealership reports $8,000/month savings vs. outsourced charging.",
    duration: "5 days",
  },
  {
    slug: "generator-backup-hospital-clinic",
    title: "Whole-Facility Generator Backup for Medical Clinic",
    location: "Springfield",
    category: "Generator Installation",
    propertyType: "Commercial",
    challenge: "A busy medical clinic required compliant backup power with automatic transfer in under 10 seconds for life-safety systems.",
    solution: "100kW natural gas generator, automatic transfer switch, load-shedding logic, and quarterly maintenance plan.",
    outcome: "Passed state health department electrical inspection. Zero patient impact during two outages since installation.",
    duration: "6 days",
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    slug: "signs-your-electrical-panel-needs-upgrade",
    title: "7 Signs Your Electrical Panel Needs an Upgrade",
    excerpt: "Flickering lights, tripped breakers, and burning smells are just some of the warning signs that your panel is overloaded and potentially dangerous.",
    category: "Safety",
    readTime: "5 min read",
    date: "2025-04-25",
    featured: true,
  },
  {
    slug: "ev-charger-home-installation-guide",
    title: "EV Charger Home Installation: What You Need to Know",
    excerpt: "Everything homeowners need to understand before installing a Level 2 EV charger — from panel requirements to permit timelines and utility rebates.",
    category: "EV",
    readTime: "8 min read",
    date: "2025-04-10",
  },
  {
    slug: "electrical-safety-checklist-homeowners",
    title: "The Complete Electrical Safety Checklist for Homeowners",
    excerpt: "A practical checklist to identify hazards in your home's electrical system — from outlets and extension cords to smoke detectors and GFCI protection.",
    category: "Safety",
    readTime: "6 min read",
    date: "2025-03-18",
  },
  {
    slug: "when-to-call-emergency-electrician",
    title: "When to Call an Emergency Electrician (And When to Wait)",
    excerpt: "Learn which electrical issues demand an immediate call and which can safely wait until regular business hours — plus what to do while you wait.",
    category: "Emergency",
    readTime: "4 min read",
    date: "2025-03-05",
  },
  {
    slug: "led-lighting-upgrade-benefits",
    title: "Why LED Lighting Upgrades Pay for Themselves in Under 2 Years",
    excerpt: "A breakdown of the energy savings, lifespan benefits and rebate programs that make LED retrofits one of the best electrical investments you can make.",
    category: "Energy Efficiency",
    readTime: "5 min read",
    date: "2025-02-20",
  },
  {
    slug: "generator-sizing-guide",
    title: "How to Choose the Right Generator Size for Your Home",
    excerpt: "Portable vs. standby, kilowatt ratings, and transfer switch types — everything you need to make the right generator decision for your needs.",
    category: "Generators",
    readTime: "7 min read",
    date: "2025-02-01",
  },
];

export const mockCatalogItems: CatalogItem[] = [
  {
    slug: "square-d-qo-200a-panel",
    title: "Square D QO 200A Load Center",
    category: "Panels & Breakers",
    description: "Industry-leading residential panel with plug-on neutral technology. Supports up to 60 circuits with full AFCI/GFCI compatibility.",
    features: ["200A main breaker", "60-circuit capacity", "AFCI/GFCI ready", "5-year warranty"],
  },
  {
    slug: "chargepoint-home-flex",
    title: "ChargePoint Home Flex EV Charger",
    category: "EV Chargers",
    description: "Flexible 16–50A Level 2 home EV charger with WiFi connectivity and energy tracking. Compatible with all EVs.",
    features: ["Adjustable 16–50A", "WiFi + app control", "Universal compatibility", "Energy tracking"],
  },
  {
    slug: "kohler-20kw-standby-generator",
    title: "Kohler 20kW Air-Cooled Standby Generator",
    category: "Generators",
    description: "Reliable whole-home backup power with automatic transfer. Runs on natural gas or propane with fast 10-second startup.",
    features: ["20kW output", "Auto transfer switch", "Natural gas / propane", "10-second startup"],
  },
  {
    slug: "lutron-caseta-smart-switch",
    title: "Lutron Caséta Smart Dimmer Kit",
    category: "Smart Lighting",
    description: "Professional-grade smart dimmer with wireless mesh technology. No neutral wire required for most installations.",
    features: ["No neutral required", "Works with Alexa/Google", "Remote dimming", "5-year warranty"],
  },
  {
    slug: "leviton-gfci-outlet",
    title: "Leviton GFCI Outlet 20A",
    category: "Outlets & Switches",
    description: "UL-listed 20A GFCI outlet with self-test technology. Required by code in kitchens, bathrooms, garages and outdoor areas.",
    features: ["20A rated", "Self-test GFCI", "Tamper resistant", "Tri-color LED indicator"],
  },
  {
    slug: "ring-intercom-doorbell",
    title: "Ring Video Doorbell Pro 2",
    category: "Smart Home",
    description: "Hardwired video doorbell with 3D motion detection and head-to-toe HD video. Requires professional electrical installation.",
    features: ["3D motion detection", "Head-to-toe video", "Hardwired", "Night vision"],
  },
];

export const mockTeam: TeamMember[] = [
  {
    name: "Robert Daniels",
    role: "Master Electrician & Founder",
    bio: "30 years of experience in residential and commercial electrical work. Licensed master electrician across 3 states.",
    certifications: ["Master Electrician License", "NFPA 70E", "OSHA 30-Hour"],
  },
  {
    name: "Jennifer Walsh",
    role: "Lead Commercial Electrician",
    bio: "15 years specializing in commercial fit-outs, data center infrastructure and industrial power systems.",
    certifications: ["Journeyman Electrician", "BICSI RCDD", "OSHA 10-Hour"],
  },
  {
    name: "Carlos Mendez",
    role: "Emergency Response Lead",
    bio: "12 years of emergency electrical service. Certified in fire investigation and arc flash hazard analysis.",
    certifications: ["Journeyman Electrician", "Arc Flash Certified", "First Aid Certified"],
  },
  {
    name: "Amanda Torres",
    role: "EV & Smart Home Specialist",
    bio: "8 years focused on EV charging infrastructure, smart home systems and renewable energy integrations.",
    certifications: ["EV Charging Installer", "Lutron Certified Pro", "Tesla Certified Installer"],
  },
];

export const mockFAQs: FAQItem[] = [
  {
    id: "1",
    question: "How quickly can you respond to an emergency?",
    answer: "Our emergency team typically arrives within 45–60 minutes for most service areas. We operate 24 hours a day, 7 days a week, 365 days a year including holidays.",
    category: "Emergency",
  },
  {
    id: "2",
    question: "Are you licensed and insured?",
    answer: "Yes. We hold a Master Electrician License, carry $2M general liability insurance, and all our technicians are fully bonded. We can provide proof of insurance on request.",
    category: "Licensing",
  },
  {
    id: "3",
    question: "Do you pull permits for your work?",
    answer: "Absolutely. We handle all permit applications and schedule inspections on your behalf. All work is inspected and signed off by the local authority having jurisdiction (AHJ).",
    category: "Process",
  },
  {
    id: "4",
    question: "How much does a panel upgrade cost?",
    answer: "A standard 200A panel upgrade typically ranges from $1,200–$3,500 depending on your current setup, panel location, and local permit fees. We provide a firm written quote before starting any work.",
    category: "Pricing",
  },
  {
    id: "5",
    question: "What areas do you serve?",
    answer: "We serve Springfield, Shelbyville, Capital City, Ogdenville, and North Haverbrook. Contact us to confirm coverage for your specific address — we're always expanding our service footprint.",
    category: "Service Areas",
  },
  {
    id: "6",
    question: "Do you offer warranties on your work?",
    answer: "Yes. We provide a 1-year labor warranty on all standard work and a 2-year warranty on panel replacements. Equipment warranties from manufacturers are passed through to you.",
    category: "Warranty",
  },
  {
    id: "7",
    question: "How do I know if I have a knob-and-tube wiring problem?",
    answer: "Common signs include cloth-wrapped wiring in the attic, no ground prong on outlets, frequent breaker trips, and a home built before 1950. Our inspection will identify knob-and-tube and outline your options.",
    category: "Safety",
  },
  {
    id: "8",
    question: "Can you install an EV charger in my condo?",
    answer: "Yes, with HOA approval. We work with condo associations regularly and can provide a load letter and insurance certificates. The installation typically takes half a day and requires a dedicated 240V circuit.",
    category: "EV",
  },
  {
    id: "9",
    question: "What payment methods do you accept?",
    answer: "We accept cash, check, all major credit cards, and bank transfer. Financing options are available for projects over $2,000 through our lending partner.",
    category: "Pricing",
  },
  {
    id: "10",
    question: "What should I do if I smell burning from an outlet?",
    answer: "Do not use that outlet. Turn off the corresponding breaker immediately. If the smell persists or you see discoloration, call our emergency line right away. Do not use the outlet until it has been inspected.",
    category: "Emergency",
  },
];
